---

language: python

python:
  - 2.7

addons:
  postgresql: 9.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get upgrade -qq -o Dpkg::Options::="--force-confold" --force-yes -y
  - sudo apt-get install -y ansible libmemcached-dev

install:
  - ansible-galaxy install -r requirements.txt --force

script:
  - sudo ansible-playbook provisioning/playbook.yml
