---

- name: Configuration of my computer
  hosts: all
  sudo: yes
  vars_files:
    - vars/apt.yml
    - vars/gitconfig.yml
  roles:
    - { role: kosssi.gitconfig, tags: git, sudo: no }
    - { role: kosssi.apt,       tags: apt      }
    - { role: kosssi.phpstorm,  tags: phpstorm }
    - { role: kosssi.composer,  tags: composer }
