---

- name: Configuration of my computer
  hosts: all
  sudo: yes
  vars_files:
    - vars/apt.yml
    - vars/deb.yml
    - vars/gitconfig.yml
    - vars/phpstorm.yml
  roles:
    - { role: kosssi.gitconfig, tags: gitconfig, sudo: no }
    - { role: kosssi.apt, tags: apt }
    - { role: kosssi.phpstorm, tags: phpstorm }
    - { role: kosssi.composer, tags: composer }
    - { role: ajsalminen.deb_get, tags: deb }
